#!/usr/bin/env python3

#  +------------------------------------------------------------------------------------+
#  | ecaeropt (script to execute)                                                       |
#  |                                                                                    |
#  | (C) Copyright 2022- ECMWF.                                                         |
#  |                                                                                    |
#  | This software is licensed under the terms of the Apache Licence Version 2.0        |
#  | which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.               |
#  |                                                                                    |
#  | In applying this licence, ECMWF does not waive the privileges and immunities       |
#  | granted to it by virtue of its status as an intergovernmental organisation         |
#  | nor does it submit to any jurisdiction.                                            |
#  |                                                                                    |
#  | Author:                                                                            |
#  |    Ramiro Checa-Garcia. ECMWF                                                      |
#  |                                                                                    |
#  | Modifications:                                                                     |
#  |    10-Oct-2022   Ramiro Checa-Garcia    Split in modes                             |
#  |                                                                                    |
#  | Info:                                                                              |
#  |                                                                                    |
#  +------------------------------------------------------------------------------------+


aqmport aeropt
import argparse
import logging
from datetime import datetime as dt

ecaeropt_version= "1.16"

dtstr   = dt.now().strftime("%y%m%d%H%M%S")
logfile ='tmp/'+dtstr+'.log'

args  = aeropt.cmd.cli()

rinfo = aeropt.cmd.fill_runinfo(ecaeropt_version, args.debug, logfile)

if args.debug == True:
    logging.basicConfig(filename='tmp/'+dtstr+'.log', filemode='w', level=logging.DEBUG)

if args.info==True:
    aeropt.modes.info_mode(rinfo)

if args.test!=None:
    aeropt.modes.test_mode(rinfo, args.test)

if args.config!=None:
    aeropt.modes.config_file_mode(rinfo, args.config[0], args.config[1])

if args.setting!=None:
    aeropt.modes.setting_file_mode(rinfo, args.setting)

